[tool.poetry]
name = "tcm"
version = "0.1.0"
description = ""
authors = ["cworld1 <cworld0@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
