# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'components/gui_origin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1714, 772)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 100, 421, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.b_verticalLayout = QtWidgets.QVBoxLayout(
            self.verticalLayoutWidget)
        self.b_verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.b_verticalLayout.setObjectName("b_verticalLayout")
        self.comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox.setMaximumSize(QtCore.QSize(16777215, 45))
        self.comboBox.setStyleSheet("QComboBox {\n"
                                    "  background-color: #ffffff;\n"
                                    "  border: 1px solid #dcdfe6;\n"
                                    "  padding: 10px;\n"
                                    "  border-radius: 7px;\n"
                                    "  font: bold 17px;\n"
                                    "}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.b_verticalLayout.addWidget(self.comboBox)
        self.comboBox_2 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_2.setMaximumSize(QtCore.QSize(16777215, 45))
        self.comboBox_2.setStyleSheet("QComboBox {\n"
                                      "  background-color: #ffffff;\n"
                                      "  border: 1px solid #dcdfe6;\n"
                                      "  padding: 10px;\n"
                                      "  border-radius: 7px;\n"
                                      "  font: bold 17px;\n"
                                      "}")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.b_verticalLayout.addWidget(self.comboBox_2)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(
            QtCore.QRect(100, 390, 281, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.c_horizontalLayout = QtWidgets.QHBoxLayout(
            self.horizontalLayoutWidget)
        self.c_horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.c_horizontalLayout.setObjectName("c_horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton.setStyleSheet("QPushButton {\n"
                                      "  background-color: #ffffff;\n"
                                      "  border: 1px solid #dcdfe6;\n"
                                      "  padding: 10px;\n"
                                      "  border-radius: 7px;\n"
                                      "  font: bold 17px;\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:hover {\n"
                                      "  background-color: #bff1d8;\n"
                                      "  color: #066335;\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:pressed,\n"
                                      "QPushButton:checked {\n"
                                      "  border-color: #44b17b;\n"
                                      "  color: #066335;\n"
                                      "}")
        self.pushButton.setObjectName("pushButton")
        self.c_horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
                                        "  background-color: #ffffff;\n"
                                        "  border: 1px solid #dcdfe6;\n"
                                        "  padding: 10px;\n"
                                        "  border-radius: 7px;\n"
                                        "  font: bold 17px;\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover {\n"
                                        "  background-color: #bff1d8;\n"
                                        "  color: #066335;\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:pressed,\n"
                                        "QPushButton:checked {\n"
                                        "  border-color: #44b17b;\n"
                                        "  color: #066335;\n"
                                        "}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.c_horizontalLayout.addWidget(self.pushButton_2)
        self.e_cameraImage = QtWidgets.QLabel(self.centralwidget)
        self.e_cameraImage.setGeometry(QtCore.QRect(490, 30, 1200, 720))
        self.e_cameraImage.setStyleSheet("background-color: rgb(221, 221, 221);\n"
                                         "border-radius:7px;")
        self.e_cameraImage.setObjectName("e_cameraImage")
        self.d_deepthImage = QtWidgets.QLabel(self.centralwidget)
        self.d_deepthImage.setGeometry(QtCore.QRect(30, 480, 431, 261))
        self.d_deepthImage.setStyleSheet("background-color: rgb(221, 221, 221);\n"
                                         "border-radius:7px;")
        self.d_deepthImage.setObjectName("d_deepthImage")
        self.a_logo = QtWidgets.QLabel(self.centralwidget)
        self.a_logo.setGeometry(QtCore.QRect(40, 30, 117, 67))
        self.a_logo.setStyleSheet("background-color: rgb(221, 221, 221);\n"
                                  "border-radius:7px;")
        self.a_logo.setObjectName("a_logo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1714, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "2"))
        self.pushButton.setText(_translate("MainWindow", "播放"))
        self.pushButton_2.setText(_translate("MainWindow", "暂停"))
        self.e_cameraImage.setText(_translate("MainWindow", "CameraImage"))
        self.d_deepthImage.setText(_translate("MainWindow", "DeepthImage"))
        self.a_logo.setText(_translate("MainWindow", "Logo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
